name: johnson2023ols_env
channels:
  - defaults
dependencies:
  - python=3.10
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - numpy=1.23.1
  - ipykernel
  - pyaml
  - requests
  - scikit-learn
  - matchpy
  - pytorch
  - torchvision
  - tensorflow
  - prettytable
  - memray
  - mxnet 
